#!/usr/bin/env bash
# ssl to my website

function get_rec_type() {
    output=$(eval "dig $2.$1")
    result_type=$(echo "$output" | grep -A1 'ANSWER SECTION:'  | awk 'FNR == 2 {print $4}')
    result_to=$(echo "$output" | grep -A1 'ANSWER SECTION:'  | awk 'FNR == 2 {print $5}')
    echo "The subdomain $2 is a $result_type record and points to $result_to";
}
#function get_rec_type1() {
#    output=$(eval "dig $2.$1")
#    result=$(echo "$output" | grep -A1 'ANSWER SECTION:'  | awk 'FNR == 2 {print $4}')
#    echo "The subdomain $2 is a $result record and points to 34.74.126.87";
#}
# function get_rec_type2() {
#     output=$(eval "dig $2.$1")
#     result=$(echo "$output" | grep -A1 'ANSWER SECTION:'  | awk 'FNR == 2 {print $4}')
#     echo "The subdomain $2 is a $result record and points to 54.227.82.19";
# }
if [ $# -eq 2 ]
then

    get_rec_type "$1" "$2"
else
    get_rec_type "$1" "www"
    get_rec_type "$1" "lb-01"
    get_rec_type "$1" "web-01"
    get_rec_type "$1" "web-02"
   
fi