#!/usr/bin/env bash
# transfer file
if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no "$4" "$1" "$3"@"$2":~/
fi
