#!/usr/bin/env bash
# this installs nginx and creates a helloworld return
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart