#!/usr/bin/env bash
# this is installs haproxy and sets it to roundrobin 
sudo apt-get update
sudo apt-get install haproxy=2.0.\*
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_default_conf.cfg
echo "
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 3966-web-01 34.74.126.87 check
    server 3966-web-02 54.227.82.19 check
    " | sudo tee -a /etc/haproxy/haproxy.cfg
sudo su
echo -e "ENABLED=1" >> etc/default/haproxy
sudo service haproxy restart
