#!/usr/bin/env bash
# this is installs haproxy and sets it to roundrobin 
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get install haproxy=2.0.\* -y
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_default_conf.cfg
echo "
backend web-backend
    balance roundrobin
    server 3966-web-1 34.74.126.87 check
    server 3966-web-2 54.227.82.19 check
    
frontend http
    bind *:80
    mode http
    default_backend web-backend
    " | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
