#!/usr/bin/env bash
# ping what is passed as argument
# https://leonardcucos.com/how-to-make-a-ping-sweep-linux-script/

if [ "$1" ]
then
ping -c 5 "$1"
else
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
