#!/usr/bin/env bash
# this is a script that connects to a server using key
ssh -i ~/.ssh/school ubuntu@34.74.126.87
#!/usr/bin/env bash
# this is a script that connects to a server using key
ssh -i ~/.ssh/school ubuntu@34.74.126.87
ssh -i ~/.ssh/school ubuntu@54.227.82.19
ssh -i ~/.ssh/aws ubuntu@44.204.28.37